// Cart functionality for displaying and managing cart items

// Initialize cart and orders in localStorage if they don't exist
if (!localStorage.getItem('cart')) {
    localStorage.setItem('cart', JSON.stringify([]));
}

if (!localStorage.getItem('orders')) {
    localStorage.setItem('orders', JSON.stringify([]));
}

// Convert cart items into an order and save to localStorage AND Supabase
async function createOrderFromCart() {
    // Get current user
    const currentUser = JSON.parse(localStorage.getItem('currentUser'));
    if (!currentUser) {
        alert('Please login to place an order!');
        window.location.href = 'index.html';
        return null;
    }
    
    // Get cart items
    const cart = JSON.parse(localStorage.getItem('cart')) || [];
    if (cart.length === 0) {
        alert('Your cart is empty!');
        return null;
    }
    
    // Calculate order totals
    const subtotal = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);
    const tax = subtotal * 0.10; // 10% tax
    const total = subtotal + tax;
    
    // Create order object with required fields
    const orderData = {
        user_name: currentUser.username,
        total_amount: total,
        status: "Pending",
        // created_at will be auto-generated by Supabase
    };
    
    try {
        // Check if Supabase is available
        if (typeof supabase === 'undefined') {
            console.log('Supabase not available, saving to localStorage only');
            // Fallback to localStorage only
            return saveOrderToLocalStorage(currentUser, cart, subtotal, tax, total);
        }
        
        // Insert order into orders table
        const { data: orderResult, error: orderError } = await supabase
            .from('orders')
            .insert([orderData])
            .select()
            .single();
        
        if (orderError) {
            console.error('Error creating order:', orderError);
            alert('Error placing order: ' + orderError.message);
            return null;
        }
        
        const orderId = orderResult.id;
        
        // Create order items array
        const orderItems = cart.map(item => ({
            order_id: orderId,
            item_name: item.name,
            quantity: item.quantity,
            price: item.price
        }));
        
        // Insert order items into order_items table
        const { data: itemsResult, error: itemsError } = await supabase
            .from('order_items')
            .insert(orderItems);
        
        if (itemsError) {
            console.error('Error creating order items:', itemsError);
            alert('Error placing order: ' + itemsError.message);
            return null;
        }
        
        // Create order object for localStorage
        const order = {
            id: orderId,
            user: {
                id: currentUser.id,
                username: currentUser.username,
                fullname: currentUser.fullname
            },
            items: [...cart], // Copy cart items
            status: "Pending", // Default status
            timestamp: new Date().toISOString(), // ISO timestamp
            subtotal: subtotal,
            tax: tax,
            total: total
        };
        
        // Save to localStorage as well for local access
        saveOrderToLocalStorage(currentUser, cart, subtotal, tax, total);
        
        console.log('Order placed successfully with ID:', orderId);
        return order;
        
    } catch (error) {
        console.error('Error placing order:', error);
        alert('Error placing order: ' + error.message);
        return null;
    }
}

// Fallback function to save order to localStorage only
function saveOrderToLocalStorage(currentUser, cart, subtotal, tax, total) {
    // Create order object with required fields
    const order = {
        id: Date.now(), // Unique order ID
        user: {
            id: currentUser.id,
            username: currentUser.username,
            fullname: currentUser.fullname
        },
        items: [...cart], // Copy cart items
        status: "Pending", // Default status
        timestamp: new Date().toISOString(), // ISO timestamp
        subtotal: subtotal,
        tax: tax,
        total: total
    };
    
    // Get existing orders
    let orders = JSON.parse(localStorage.getItem('orders')) || [];
    
    // Add new order
    orders.push(order);
    
    // Save updated orders to localStorage
    localStorage.setItem('orders', JSON.stringify(orders));
    
    // Clear cart
    localStorage.setItem('cart', JSON.stringify([]));
    
    return order;
}

// Load and display cart items
function loadCartItems() {
    const cart = JSON.parse(localStorage.getItem('cart')) || [];
    const container = document.getElementById('cartItemsContainer');
    
    if (!container) return;
    
    if (cart.length === 0) {
        container.innerHTML = '<p>Your cart is empty. <a href="menu.html">Continue shopping</a></p>';
        updateCartSummary();
        return;
    }
    
    container.innerHTML = cart.map(item => `
        <div class="cart-item-card" data-id="${item.itemId}">
            <div class="cart-item-info">
                <h3>${item.name}</h3>
                <p class="cart-item-price">₹${item.price.toFixed(2)} × ${item.quantity}</p>
                <p class="cart-item-total">Total: ₹${(item.price * item.quantity).toFixed(2)}</p>
            </div>
            <button class="remove-item-btn" data-id="${item.itemId}">Remove</button>
        </div>
    `).join('');
    
    // Add event listeners to remove buttons
    document.querySelectorAll('.remove-item-btn').forEach(button => {
        button.addEventListener('click', function() {
            const itemId = parseInt(this.getAttribute('data-id'));
            removeItemFromCart(itemId);
        });
    });
    
    updateCartSummary();
}

// Update cart summary (subtotal, tax, total)
function updateCartSummary() {
    const cart = JSON.parse(localStorage.getItem('cart')) || [];
    const subtotalElement = document.getElementById('subtotal');
    const taxElement = document.getElementById('tax');
    const totalElement = document.getElementById('total');
    
    if (!subtotalElement || !taxElement || !totalElement) return;
    
    // Calculate subtotal
    const subtotal = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);
    
    // Calculate tax (10%)
    const tax = subtotal * 0.10;
    
    // Calculate total
    const total = subtotal + tax;
    
    // Update display
    subtotalElement.textContent = `₹${subtotal.toFixed(2)}`;
    taxElement.textContent = `₹${tax.toFixed(2)}`;
    totalElement.textContent = `₹${total.toFixed(2)}`;
}

// Remove item from cart
function removeItemFromCart(itemId) {
    let cart = JSON.parse(localStorage.getItem('cart')) || [];
    cart = cart.filter(item => item.itemId !== itemId);
    
    // Save updated cart to localStorage
    localStorage.setItem('cart', JSON.stringify(cart));
    
    // Reload cart display
    loadCartItems();
}

// Place order function
async function placeOrder() {
    // Create order using the updated function
    const order = await createOrderFromCart();
    
    if (order) {
        // Redirect to orders page
        window.location.href = 'orders.html';
    }
}

// Initialize page
document.addEventListener('DOMContentLoaded', function() {
    loadCartItems();
    
    // Set up place order button
    const placeOrderBtn = document.getElementById('placeOrderBtn');
    if (placeOrderBtn) {
        placeOrderBtn.addEventListener('click', placeOrder);
    }
});